#!/usr/bin/env bash
#===----------------------------------------------------------------------===##
#
# Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
#===----------------------------------------------------------------------===##

set -eu
set -o pipefail

cat <<EOF
- agents:
    queue: ${INPUT_BUILDKITE_QUEUE:-windows}
  artifact_paths:
  - artifacts/**/*
  - '*_result.json'
  - build/test-results.xml
  commands:
  - sccache --zero-stats
  - C:\BuildTools\Common7\Tools\VsDevCmd.bat -arch=amd64 -host_arch=amd64
  - rm /s /q ./build && mkdir ./build && cd ./build
  - cmake ../llvm \
    -G Ninja \
    -D CMAKE_BUILD_TYPE=Release \
    -D LLVM_ENABLE_PROJECTS="${INPUT_LLVM_ENABLE_PROJECTS:-llvm}" \
    -D CMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -D LLVM_ENABLE_LLD=ON \
    -D CMAKE_C_COMPILER_LAUNCHER=sccache -D CMAKE_CXX_COMPILER_LAUNCHER=sccache \
    -D LLVM_ENABLE_ASSERTIONS=ON -D LLVM_BUILD_EXAMPLES=ON \
    -D LLDB_INCLUDE_TESTS=OFF \
    -D COMPILER_RT_BUILD_LIBFUZZER=OFF -D COMPILER_RT_BUILD_ORC=OFF \
    -D LLVM_LIT_ARGS="-v --xunit-xml-output test-results.xml"
  - ninja -v "${INPUT_NINJA_COMMAND:-check_all}"
  key: windows
  label: ':windows: windows x64'
  retry:
    automatic:
    - exit_status: -1
      limit: 2
    - exit_status: 255
      limit: 2
  timeout_in_minutes: 150
EOF