#!/usr/bin/env bash
#===----------------------------------------------------------------------===##
#
# Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
#===----------------------------------------------------------------------===##

set -eu
set -o pipefail

cat <<EOF
- agents:
    queue: "${INPUT_BUILDKITE_QUEUE:-linux-test}"
  commands:
  - sccache --zero-stats
  - rm -rf ./build && mkdir -p ./build && cd ./build
  - echo "--- configure"
  - cmake ../llvm \
    -D BOLT_CLANG_EXE=/usr/bin/clang \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_C_COMPILER_LAUNCHER=sccache \
    -D CMAKE_C_COMPILER=clang \
    -D CMAKE_CXX_COMPILER_LAUNCHER=sccache \
    -D CMAKE_CXX_COMPILER=clang++ \
    -D CMAKE_CXX_FLAGS=-gmlt \
    -D COMPILER_RT_BUILD_LIBFUZZER=OFF \
    -D LLDB_INCLUDE_TESTS=OFF \
    -D LLVM_BUILD_EXAMPLES=ON \
    -D LLVM_ENABLE_ASSERTIONS=ON \
    -D LLVM_ENABLE_PROJECTS="${INPUT_LLVM_ENABLE_PROJECTS:-llvm}" \
    -D LLVM_LIT_ARGS="-v --xunit-xml-output test-results.xml --time-tests"
    -G Ninja \
  - echo "--- test"
  - ninja -v check-all
  - echo "--- sccache stats"
  - sccache --show-stats
  env:
    CC: "clang"
    CXX: "clang++"
    LD: "LLD"
  key: linux
  label: ':linux: linux x86'
  retry:
    automatic:
    - exit_status: -1
      limit: 2
    - exit_status: 255
      limit: 2
  timeout_in_minutes: 120
EOF